es:
  image: elasticsearch
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - es:elasticsearch

fluentd:
  image: tinhtun/fluentd-elasticsearch
  ports:
    - 24224:24224
    - 24224:24224/udp
  volumes:
    - ./fluentd:/fluentd/etc
  environment:
    - ELASTICSEARCH_HOST=es
    - FLUENTD_CONF=fluent.conf 
  links:
    - es:es